version: '2.2'
services:
    suricata:
        image: stamus/suricata
        volumes:
            - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
            - ./suricata:/var/log/suricata:rw
            - ./suricata/run/:/var/run/suricata:rw
            - ./config/suricata/ethtool.conf:/etc/supervisor/conf.d/ethtool.conf:ro
            - ./scirius/:/etc/suricata/rules:rw
        cap_add:
            - NET_ADMIN
            - NET_RAW
        privileged: true
        # TODO set your suricata iface here
        environment:
            - SURICATA_ARGS="--af-packet=wlp0s20f3"
        network_mode: host

    elasticsearch:
        build: ./docker/elasticsearch
        command: -Des.network.bind_host=elasticsearch -Des.index.number_of_replicas=0
        volumes:
            - ./elasticsearch:/usr/share/elasticsearch/data:rw


    logstash:
        image: logstash:2
        links:
            - elasticsearch
        command: /opt/logstash/bin/logstash -f /etc/logstash/conf.d/
        volumes:
            - ./config/logstash:/etc/logstash:ro
            - ./suricata:/var/log/suricata:ro
        hostname: suricata


    kibana:
        build: ./docker/kibana
        links:
            - elasticsearch


    scirius:
        image: stamus/scirius:elk5
        volumes:
            - ./config/scirius:/etc/scirius:ro
            - ./config/suricata/suricata.yaml:/etc/suricata/suricata.yaml:ro
            - ./scirius:/etc/suricata/rules:rw
            - ./suricata/run:/var/run/suricata:ro
            - ./backups:/var/backups:rw
            # TODO uncomment correctly set path to scirius git tree on host below
            # to run a specific scirius version
            #- /path/to/git/stamus/scirius/:/opt/selks/scirius/:ro
        links:
            - elasticsearch
            - kibana
            - evebox
        volumes_from:
            - sciriusdata
            - sciriusstatic


    sciriusdata:
        image: busybox
        command: /bin/true
        volumes:
            - /sciriusdata


    sciriusstatic:
        image: busybox
        command: /bin/true
        volumes:
            - /sciriusstatic


    evebox:
        image: jasonish/evebox:0.11.1
        links:
            - elasticsearch

        ports:
            - 5636:5636
        command: -e http://elasticsearch:9200

    nginx:
        image: nginx
        ports:
            - 443:443
        volumes:
            - ./config/nginx/amsterdam.conf:/etc/nginx/conf.d/default.conf:ro
            - ./config/nginx/ssl/:/etc/nginx/ssl/:ro
        links:
            - scirius
        volumes_from:
            - sciriusstatic
